# Generated by Django 2.2.6 on 2020-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201017_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Пиши тут!', verbose_name='Комментарии'),
        ),
    ]
